{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-agent
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-agent
    spec:
      hostNetwork: {{ .Values.agent.hostNetwork }}
      dnsPolicy: {{ .Values.agent.dnsPolicy }}
      containers:
        - name: otel-agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          command:
            - "/otelcol-contrib"
            - "--config=/conf/collector.yaml"
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-agent-config
{{- end }}
