variables:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Bearer%20${OTEL_CI_AUTH_SECRET}"

stages:
  - lint
  - build
  - deploy

run-build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - bin/
